# Site
name: "Henry Buron"
title: "Henry's Portfolio"
description: "Robotics Software Engineer — autonomy, SLAM, and computer vision"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: https://henryburon.github.io
baseurl: 
google_analytics:
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Henry:
    name: Henry Buron
    display_name: Henry Buron
    gravatar:
    email:
    LinkedIn: https://www.linkedin.com/in/henryburon/
    description: 

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude: [post_template.md, changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, docker-compose.yml, vendor/bundle]
